# Generated by Django 4.0 on 2022-01-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='Blog',
        ),
    ]
